"""Process raw markdown files into AI-ready context text."""

SEPARATOR = "\n" + "=" * 60 + "\n"

CONTEXT_HEADER = """# {framework} Documentation Context
# Generated by DocFeed — Feed your AI the freshest docs.
# Modules: {modules}
# Files: {file_count}
"""


def format_single_file(path: str, content: str) -> str:
    """Format a single file into a context block."""
    return f"## File: {path}\n\n{content.strip()}"


def build_context(
    framework_name: str,
    module_names: list[str],
    file_contents: dict[str, str],
) -> str:
    """Assemble all file contents into a single context string.

    The output is designed to be directly pasted into an AI tool's
    context window with clear file boundaries.
    """
    header = CONTEXT_HEADER.format(
        framework=framework_name,
        modules=", ".join(module_names),
        file_count=len(file_contents),
    )

    blocks = [
        format_single_file(path, content)
        for path, content in sorted(file_contents.items())
    ]

    return header + SEPARATOR + SEPARATOR.join(blocks) + "\n"